name: Deploy to S3 on Release

on:
  release:
    types: [published]
    # Only run this workflow when a release is published (not when a draft is created)

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Change into homepage directory
        run: cd homepage

      - name: Install dependencies
        run: npm install

      - name: Build the App
        run: npm run build

      - name: Change back into the root directory
        run: cd ../

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          homepage/build/* -f
          aws s3 sync ./homepage/build/* s3://app.vlabs.ac.in --delete

      - name: invalidate cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id EG68U5E0MPHRX --paths  "/*" "/"

